import mongoose from 'mongoose';

const planConfigSchema = new mongoose.Schema({
  courseName: { type: String, default: "MERN Stack" },
  courseTagline: { type: String, default: "Full Stack Web Development" },
  oneTimePrice: { type: Number, default: 6000 },
  oneTimeOriginalPrice: { type: Number, default: 15000 },
  heroOfferPrice: { type: Number, default: 6000 },
  installment1Price: { type: Number, default: 3200 },
  installment2Price: { type: Number, default: 3200 },
  discountPercent: { type: Number, default: 10 },
  oneTimeDiscountPercent: { type: Number, default: 10 },
  installment1DiscountPercent: { type: Number, default: 10 },
  installment2DiscountPercent: { type: Number, default: 10 },
  oneTimeFeatures: { type: [String], default: [] },
  installmentFeatures: { type: [String], default: [] },
  courses: { type: [String], default: ["Frontend Developer", "Backend Developer", "MERN Stack"] },
  colleges: { type: [String], default: ["PDPS College", "BUIT", "Other"] },
  cities: { type: [String], default: ["Bhopal", "Indore", "Jabalpur", "Other"] },
  totalSeats: { type: Number, default: 50 },
  manualSeatsOffset: { type: Number, default: 32 },
  manualSeatsOffsetRegistrationsCount: { type: Number, default: 0 },
  seatsOffsetUpdatedAt: { type: Date, default: Date.now },
  batchStartDate: { type: String, default: "21 September 2026" },
  offerTimerHours: { type: Number, default: 4 },
  offerTimerMode: { type: String, default: "daily" },
  offerTargetDate: { type: String, default: "" },
  whatsappNumber: { type: String, default: "919876543210" },
  whatsappMessage: { type: String, default: "Hello BeanGate IT Solutions, I am interested in the MERN Stack Course!" },
  whatsappEnabled: { type: Boolean, default: true },
  whatsappLabel: { type: String, default: "Need Help? Chat with us" },
  whatsappPosition: { type: String, default: "bottom-right" },
  whatsappType: { type: String, default: "number" },
  whatsappGroupLink: { type: String, default: "" },
  contactPhone: { type: String, default: "+91 74711 12020, +91 97527 40090" },
  contactEmail: { type: String, default: "info@beangates.com" },
  contactAddress: { type: String, default: "Flat No. A-4 / 501, Kokta Transport Nagar,\nBhopal, Madhya Pradesh – 462022" },
  facebookUrl: { type: String, default: "" },
  instagramUrl: { type: String, default: "" },
  youtubeUrl: { type: String, default: "" },
  linkedinUrl: { type: String, default: "" },
});

export default mongoose.model('PlanConfig', planConfigSchema);
